apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      imagePullSecrets:
      - name: dockerhub      
      containers:
        - name: order
          image: docker.io/hiondal/order:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "18080"
          envFrom:
          - configMapRef:
              name: order
          - secretRef:
              name: order
                            
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: order
data:
  DB_SERVER: mysql
  DB_PORT: "3306"
  DB_NAME: "order"
  QUEUE_SERVER: 165.192.105.60
  QUEUE_PORT: "5672"
  CUSTOMER_DB_HOST: customer
  CUSTOMER_DB_PORT: "8080"
  PRODUCT_DB_HOST: product
  PRODUCT_DB_PORT: "8080"
  DELIVERY_DB_HOST: delivery
  DELIVERY_DB_PORT: "8080"

---

kind: Secret
apiVersion: v1
metadata:
  name: order
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: P@ssw0rd$
  QUEUE_USERNAME: admin
  QUEUE_PASSWORD: P@ssw0rd$ 
---

apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: order
      port: 8080
      targetPort: 18080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: order-hiondal.165.192.105.60.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: order
                port: 
                  number: 8080
                  